### ISSUE TITLE
The lines of Listings have an inconsistent width 

### ISSUE THREAD

**Issue by xFrednet** [TobiasWrigstad/thesis-template#3]
Listings have lines above the caption and around the float. The width of these seem to be inconsistent. I don't have a minimal reproducible example, but you should be able to access my thesis, at [47da83d](https://github.com/xFrednet/uu-thesis-borrow-patterns/tree/47da83d2d74ca30a54669041a531a05d748dbb02). The screenshots have been taken after a `make clean; make cycle`:

Listing 2.1 on Page 4 extends over the edge of the text column:

![image](https://github.com/TobiasWrigstad/thesis-template/assets/17087237/65e6d386-0302-4a75-85ab-524ffa6e8e41)

Listing 2.2 on Page 4 is only as wide as the text:

![image](https://github.com/TobiasWrigstad/thesis-template/assets/17087237/54a9ed00-692e-494b-ae1f-45073fedf223)
 
All listings on odd pages, like page 5, always seem to expand over the entire page:

![image](https://github.com/TobiasWrigstad/thesis-template/assets/17087237/13862b6d-1ca6-410c-882d-2b79ab11c9d0)

I would prefer if all listings had the width of the text, regardless of the page.

The build log doesn't seem to have any warnings regarding potential reasons. This is just a wild guess, but the different widths on even pages might be a result of latex commands inserted via the `@` symbol.

Note that my version is from 2 months ago, so you might have already fixed this on master. Sorry if that's the case :sweat_smile:

**Comment by xFrednet** [comment]
Ping @TobiasWrigstad, have you had the time to look at this issue? It would be nice if this could be fixed for my final thesis submission

**Comment by malyzajko** [comment]
In my experiments, it seems that if one changes
`\begin{listing*}[t]`
into 
`\begin{listing}[t]`
then this fixes the problem.

**Comment by TobiasWrigstad** [comment]
@malyzajko I can reproduce. Thanks for that comment. Looking at why that was, I realise that there was a `listings*` environment defined that tries in a hacky way to adjust the lines to fill the page width, not just the text width. It checks whether the float is on a even or odd page to do so, but I'm thinking that floats may be flushed by LaTeX to a different page *after* the checking, which is one reason why we are seeing strange results. I'll investigate now. @xFrednet Sorry for pushing this off for so long!

**Comment by TobiasWrigstad** [comment]
Yes, I have now confirmed that the problem was indeed that the float code checked whether the page was odd or even before the float's final position was defined.

**Comment by TobiasWrigstad** [comment]
This problem is pretty difficult to solve it seems, without bringing out very big guns. I think @malyzajko 's fix is good for now. Let's change the template so lines do not extend into the margin at all. I probably should look at tufte-latex for some good ideas on how to do this the hard way.

**Comment by TobiasWrigstad** [comment]
If you pull the newest version of the template, everything should work without lines extending into the margin, even without @malyzajko 's fix. Please confirm!

**Comment by malyzajko** [comment]
Yes, it looks good now!

**Comment by xFrednet** [comment]
Can also confirm, everything looks good now! Thank you for the fix!

I'll close the issue, since it has been resolved
